"""Update user model with standard fields

Revision ID: 35f91021ceef
Revises: 4be086396e93
Create Date: 2025-12-14 13:46:25.476600

"""

# revision identifiers, used by Alembic.
revision = '35f91021ceef'
down_revision = '4be086396e93'
branch_labels = None
depends_on = None


from alembic import op
import sqlalchemy as sa
import sqlmodel


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remark')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###
